Docs
Garvys/rustfst pull request #236
Opened 2023-02-15 19:19 UTC by dhdaines

Various documentation improvements

2023-02-15 21:34 UTC, dhdaines commented
Hi! Here's a preliminary cleanup of the documentation to:

- Add an introduction with a lot of useful links to lower-level pages
- Fill in missing descriptions
- Make the descriptions of algorithms more consistent
- List a number of differences from OpenFST that are useful to know

2023-02-22 17:25 UTC, Garvys requested changes
Very nice !!! Thanks for taking the time of doing this ! 
Small typos and then I'm good for a merge!
(Sorry for the late answer, missed the notification 😬 )

2023-02-22 17:25 UTC, Garvys commented on rustfst/src/algorithms/optimize.rs
> +/// General optimization (determinization and minimiaztion) of a WFST
typo

2023-02-22 17:25 UTC, Garvys commented on rustfst/src/algorithms/inversion.rs
> +/// Inverts the transduction corresponding to an FST
`Invert`

2023-02-22 17:50 UTC, dhdaines commented
Done! I will probably write some more, will make another PR for those later.

2023-02-22 17:52 UTC, Garvys commented
Great !! Thanks so much 💪

2023-02-22 17:52 UTC, Garvys approved these changes
🚀

2023-02-23 10:03 UTC, merged