Fix up Clippy issues and do some manual cleanups
Garvys/rustfst pull request #255
Opened 2024-04-27 07:58 UTC by dzhu

Clippy has to be run twice to reproduce these results (to cover some
spots that get hit by one lint and then another).

Remaining Clippy issues:

- A lot of instances of `not_unsafe_ptr_arg_deref` under
  `rustfst-ffi`. Fixing those would require either skipping the lint at
  the top level, which Clippy strongly recommends against, or adding
  `unsafe` to many functions, which would be a big change textually and
  I think also technically a breaking change.

- Unused tuple members in `CConstFst` and `CConcatFst`. It's not clear
  what those are supposed to be doing, but they're `pub`, so I'll just
  leave them untouched.

2024-04-27 14:33 UTC, Garvys commented
Hello ! 
Thanks for the contribution :-)
So most of the clippy issues where from a new more recent clippy that the one I used in the CI.
I just bumped the version of rust to 1.74.0 (in order to be able clap) and stumbled on your PR 😢 
As a result I fixed the lints for 1.74.0.
I see in your PR that you fixed others as well so feel free to merge main and then we can definitely merge your changes on main 👍

2024-04-27 14:34 UTC, Garvys commented
Also note that if you wanna reproduce the most recent clippy lint in the CI, you can bump the rust version used for running clippy here https://github.com/Garvys/rustfst/blob/cc9b58f8ea0761a3e449d6a8084d821fd12149f6/.github/workflows/native.yml#L139

2024-04-29 05:07 UTC, dzhu commented
Wow, what timing on my part -- congratulations on releasing 1.0! I've rebased this PR onto the latest main and bumped the CI versions.

2024-04-29 13:25 UTC, Garvys commented on .github/workflows/native.yml
> +        rust: [1.77.2, stable]
```suggestion
        rust: [1.74.0, stable]
```
I would keep this one to 1.74.0 as it checks the compatibility with this version of the compiler

2024-04-29 13:27 UTC, Garvys requested changes
One small comment but appart from that it seems good to me 👍

2024-05-10 08:41 UTC, dzhu commented
Okay, I got everything up to date with the newest stable Rust. I just realized that there are more things found by `cargo clippy --all-targets` that are not coming up from `cargo clippy`, but I will declare those out of scope for this PR because one of them is the top-level `#[warn(missing_docs)]` that should be `#![warn(missing_docs)]`, and fixing that brings up quite a large number of things that are missing documentation.

2024-05-13 14:35 UTC, Garvys approved these changes
Thanks!

2024-05-13 14:36 UTC, merged